# Generated by Django 4.2.7 on 2023-12-04 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0002_alter_event_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_admin',
            new_name='organizer',
        ),
    ]
