# Generated by Django 4.2.7 on 2023-12-05 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0004_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='date_registered',
            field=models.DateField(auto_now_add=True),
        ),
    ]
